import 'package:supabase_flutter/supabase_flutter.dart';

const String supabaseUrl = 'https://fpibgsacigsjzdtrtkmm.supabase.co';
const String supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwaWJnc2FjaWdzanpkdHJ0a21tIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzMTU2NzcsImV4cCI6MjAwODg5MTY3N30.vzKk7x6l3wYMXnO-dShJq4UOcoQ_F5lvD_iYTb9NhJo';